"""
Demo Data Service

Creates sample memories for new users to demonstrate Orivory features.
Called on first login or when user requests demo data.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime, timedelta
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.memory import Memory
from app.retrieval.memory.namespaces import personal_namespace
from app.retrieval.memory.visibility import namespace_predicate

log = logging.getLogger(__name__)


# Sample memories for different use cases
SAMPLE_MEMORIES = [
    {
        "title": "Getting Started with Orivory",
        "content": """Welcome to Orivory! Here's how to get the most out of your second brain:

1. **Quick Capture**: Use the quick capture bar (⌘K) to instantly save thoughts, links, or notes. They'll be automatically organized.

2. **Ask Questions**: Type questions in natural language. Orivory understands context and finds relevant memories across all your sources.

3. **Discover Connections**: The Discovery feature finds hidden relationships between your memories that you might have missed.

4. **Connect Sources**: Link Gmail, Notion, Google Drive, and other apps for automatic memory capture.

5. **Proactive Insights**: AI surfaces patterns and insights from your knowledge base, helping you see connections you didn't know existed.

**Tips**:
- Pin important memories to keep them top of mind
- Use tags to organize related content
- Review insights regularly to discover new connections
""",
        "summary": "Complete guide to using Orivory features",
        "tags": ["getting-started", "tutorial", "Orivory"],
        "source_type": "manual_note",
    },
    {
        "title": "Weekly Review Process",
        "content": """My weekly review process using Orivory:

**Monday Morning (30 min)**:
- Review last week's key memories
- Check new insights generated by AI
- Identify patterns across projects

**Wednesday Check-in (15 min)**:
- Quick scan of recent captures
- Follow up on flagged items
- Update priorities

**Friday Wrap-up (20 min)**:
- Capture weekly accomplishments
- Tag and organize new memories
- Preview upcoming week

**Tools I Use**:
- Quick capture for rapid note-taking
- Discovery to find cross-project connections
- Insights to see what AI discovered for me
""",
        "summary": "Structured weekly review workflow",
        "tags": ["productivity", "workflow", "review"],
        "source_type": "manual_note",
    },
    {
        "title": "Project: Q4 Marketing Campaign",
        "content": """Q4 Marketing Campaign planning document:

**Objectives**:
- Increase brand awareness by 30%
- Generate 500 qualified leads
- Launch before holiday season

**Target Audiences**:
1. Enterprise decision makers
2. SMB owners
3. Developer community

**Key Messages**:
- AI-powered knowledge management
- Save 5+ hours per week
- Seamless integration with existing tools

**Timeline**:
- Oct: Campaign planning and creative development
- Nov: Launch and initial outreach
- Dec: Optimization based on performance data

**Budget**: $50,000 allocated
""",
        "summary": "Q4 marketing campaign planning",
        "tags": ["marketing", "campaign", "q4", "planning"],
        "source_type": "manual_note",
    },
    {
        "title": "Meeting Notes: Product Strategy",
        "content": """Product Strategy Meeting - October 15

**Attendees**: CEO, CTO, Head of Product, Engineering Lead

**Key Decisions**:
1. Prioritize mobile app by Q1
2. Focus on collaboration features
3. Reduce enterprise feature scope

**Action Items**:
- [ ] Schedule mobile UX research
- [ ] Draft collaboration feature spec
- [ ] Review engineering estimates

**Concerns Raised**:
- Timeline is aggressive
- Mobile team needs additional hire
- Enterprise customers waiting for features

**Next Steps**:
- Engineering to provide detailed estimates by Friday
- Product to finalize mobile MVP scope
- Budget discussion next week
""",
        "summary": "Product strategy decisions and action items",
        "tags": ["meeting", "product", "strategy", "action-items"],
        "source_type": "manual_note",
    },
    {
        "title": "Research: AI Memory Systems",
        "content": """Research on AI-powered memory and knowledge management:

**Key Concepts**:
- **Semantic Memory**: Storing meaning, not just text
- **Episodic Memory**: Capturing experiences and context
- **Associative Retrieval**: Finding connections between ideas

**Competitive Analysis**:
- Notion: Good for structured data, weak on connections
- Obsidian: Powerful linking but manual
- Roam: Strong bidirectional links, steep learning curve
- Orivory: AI-powered automatic discovery

**Technical Approaches**:
1. Vector embeddings for semantic search
2. Knowledge graphs for relationship mapping
3. LLM summarization for insight generation
4. Temporal weighting for recency

**User Needs**:
- Zero-friction capture
- Automatic organization
- Proactive recommendations
- Private and secure
""",
        "summary": "Research on AI memory and knowledge systems",
        "tags": ["research", "ai", "knowledge-management", "competitors"],
        "source_type": "manual_note",
    },
    {
        "title": "Book Notes: Atomic Habits",
        "content": """Atomic Habits by James Clear - Key Takeaways:

**The Four Laws of Behavior Change**:
1. **Make it Obvious** - Design your environment
2. **Make it Attractive** - Pair with something enjoyable
3. **Make it Easy** - Reduce friction
4. **Make it Satisfying** - Track your progress

**Key Concepts**:
- **Habit Stacking**: "After I [CURRENT HABIT], I will [NEW HABIT]"
- **Environment Design**: Make good habits obvious and easy
- **Identity-Based Habits**: Focus on who you want to become
- **The Two-Minute Rule**: Scale down habits to 2 minutes

**Application to Orivory**:
- Set daily reminder to capture notes
- Create quick capture shortcut on phone
- Use Orivory as part of morning routine
- Build "review insights" as weekly habit
""",
        "summary": "Key concepts from Atomic Habits",
        "tags": ["books", "habits", "productivity", "self-improvement"],
        "source_type": "manual_note",
    },
    {
        "title": "API Integration Notes",
        "content": """Orivory API Integration Guide:

**Authentication**:
```python
headers = {
    "Authorization": f"Bearer {token}",
    "Content-Type": "application/json"
}
```

**Key Endpoints**:
- `POST /api/v1/memories` - Create memory
- `GET /api/v1/memories` - List memories
- `GET /api/v1/discovery/graph` - Get knowledge graph
- `GET /api/v1/insights` - Get AI insights
- `POST /api/v1/search` - Semantic search

**Rate Limits**:
- 60 requests per minute
- 1000 requests per day

**Best Practices**:
1. Batch operations when possible
2. Cache frequently accessed data
3. Use webhooks for real-time updates
4. Implement exponential backoff for retries
""",
        "summary": "API integration guide and best practices",
        "tags": ["api", "development", "integration", "technical"],
        "source_type": "manual_note",
    },
    {
        "title": "Personal Goals Q4 2024",
        "content": """Q4 2024 Personal Goals:

**Professional**:
- Launch Orivory mobile app
- Grow user base to 10,000 active users
- Establish thought leadership in AI productivity space
- Ship 3 major feature releases

**Learning**:
- Complete machine learning specialization
- Read 12 books (3/month)
- Learn Rust programming
- Write 4 technical blog posts

**Health**:
- Exercise 4x per week consistently
- Maintain 7+ hours of sleep
- Meditation practice daily (10 min minimum)
- Cook at home 5 days per week

**Relationships**:
- Weekly calls with family
- Monthly dinner with friends
- Quarterly team offsite events

**Finance**:
- Max out retirement contributions
- Build 6-month emergency fund
- Start investing in real estate
""",
        "summary": "Q4 2024 goals across all life areas",
        "tags": ["goals", "planning", "q4", "personal"],
        "source_type": "manual_note",
    },
]


async def create_demo_memories(
    user_id: UUID,
    db: AsyncSession,
) -> list[Memory]:
    """
    Create demo memories for a new user.

    This helps new users understand Orivory's capabilities
    by providing sample data that demonstrates various features.
    """
    log.info(f"Creating demo memories for user {user_id}")

    memories = []
    base_time = datetime.now(UTC) - timedelta(days=7)

    for i, memory_data in enumerate(SAMPLE_MEMORIES):
        # Stagger the capture times
        captured_at = base_time + timedelta(hours=i * 4)

        memory = Memory(
            user_id=user_id,
            title=memory_data["title"],
            content=memory_data["content"],
            summary=memory_data.get("summary"),
            tags=memory_data.get("tags", []),
            source_type=memory_data.get("source_type", "manual_note"),
            captured_at=captured_at,
            indexed_at=datetime.now(UTC),
        )

        db.add(memory)
        memories.append(memory)

    await db.commit()

    # Refresh to get IDs
    for memory in memories:
        await db.refresh(memory)

    log.info(f"Created {len(memories)} demo memories for user {user_id}")
    return memories


async def check_user_has_memories(user_id: UUID, db: AsyncSession) -> bool:
    """Check if user has memories in their OWN namespace (P4a/T5).

    Reads ``memories`` like any other surface, so it carries the namespace
    boundary: a row outside the caller's namespace is not a memory the caller
    has (P4a: one namespace, so this is the same answer the pre-P4 read gave).
    """
    result = await db.execute(
        select(Memory.id).where(
            Memory.user_id == user_id,
            namespace_predicate(personal_namespace(user_id)),
        ).limit(1)
    )
    return result.scalar_one_or_none() is not None


async def seed_user_demo_data(
    user_id: UUID,
    db: AsyncSession,
) -> dict:
    """
    Seed demo data for a user if they don't have any.

    Returns info about what was created.
    """
    has_memories = await check_user_has_memories(user_id, db)

    if has_memories:
        log.info(f"User {user_id} already has memories, skipping demo data")
        return {"created": False, "reason": "user_has_existing_data"}

    memories = await create_demo_memories(user_id, db)

    return {
        "created": True,
        "memory_count": len(memories),
        "memory_titles": [m.title for m in memories],
    }
